# configs/test_1episode_tqc.yaml
# TQC (Truncated Quantile Critics) 테스트용 설정 (1 episode)

seed: 42
device: cpu  # 빠른 테스트를 위해 CPU 사용

# 데이터 설정
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']

  # 날짜 기반 설정
  start: "2023-01-01"      # 전체 데이터 시작
  end: "2024-06-30"        # train+val 종료
  test_start: "2024-07-01" # 테스트 시작
  test_end: "2024-12-31"   # 테스트 종료
  val_ratio: 0.2           # train에서 val 분리 비율
  interval: '1d'
  cache: true

# 환경 설정
env:
  initial_balance: 1000000
  transaction_cost: 0.001
  max_leverage: 1.0
  window_size: 20

# 특성 추출
feature_dim: 12

# 오프라인 학습 - IQL 사용 (TQC와 잘 어울림)
offline:
  method: 'iql'  # IQL 사용
  epochs: 1  # 1 epoch만
  batch_size: 256

  # IQL 전용
  expectile: 0.7
  temperature: 3.0

  # TD3+BC 전용 (사용 안 함)
  bc_weight: 2.5
  policy_delay: 2
  normalize_q: true

# B-Cell (TQC)
bcell:
  # ⭐ TQC 알고리즘 선택
  algorithm: 'TQC'

  # 네트워크
  hidden_dims: [256, 256]

  # TQC 설정
  n_critics: 2  # TQC는 일반적으로 적은 수의 critics 사용
  n_quantiles: 25  # 분위수 개수
  top_quantiles_to_drop_per_net: 2  # 상위 2개 분위수 제거 (보수적 추정)
  quantile_embedding_dim: 64  # 분위수 임베딩 차원
  utd_ratio: 1  # TQC는 표준 업데이트 빈도 사용

  # 학습
  actor_lr: 3e-4
  critic_lr: 3e-4
  alpha_lr: 3e-4
  batch_size: 256

  # RL
  gamma: 0.99
  tau: 0.005
  alpha: 0.2

  # 위기 대응
  crisis_threshold: 0.7

  # 버퍼
  buffer_size: 100000

# T-Cell
tcell:
  contamination: 0.1
  n_estimators: 100
  window_size: 100

# Memory Cell
memory:
  capacity: 1000
  k_neighbors: 5

# 학습 설정
online_episodes: 1  # ⭐ 핵심 변경 - 1 episode만
skip_offline: false  # 오프라인도 테스트
early_stopping_patience: 20

# Ablation study
ablation:
  use_tcell: true
  use_memory: true
  use_xai: true
  offline_method: 'iql'  # IQL 명시

# 기타
log_level: 'INFO'
save_freq: 10

# 목표 메트릭
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.25
  cvar_95: -0.02

# 베이스라인 설정
baselines:
  equal_weight:
    enabled: true
  standard_sac:
    enabled: false  # TQC 테스트시 비활성화