# 체크포인트 저장 테스트용 설정

# 시스템 설정
seed: 42
device: cpu

# 데이터 설정
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL']

  # 날짜 기반 설정
  start: "2023-01-01"      # 전체 데이터 시작
  end: "2024-06-30"        # train+val 종료
  test_start: "2024-07-01" # 테스트 시작
  test_end: "2024-12-31"   # 테스트 종료
  val_ratio: 0.2           # train에서 val 분리 비율
  interval: '1d'
  cache: true

# 환경 설정
env:
  initial_balance: 1000000
  transaction_cost: 0.001
  max_leverage: 1.0
  window_size: 20

# 오프라인 사전학습
offline:
  method: 'td3bc'
  epochs: 1
  batch_size: 256
  expectile: 0.7
  temperature: 3.0
  bc_weight: 2.5
  policy_delay: 2
  normalize_q: true

# B-Cell 설정 (REDQ)
bcell:
  algorithm: 'REDQ'
  hidden_dims: [256, 256]
  n_critics: 10
  m_sample: 2
  utd_ratio: 20
  actor_lr: 3e-4
  critic_lr: 3e-4
  alpha_lr: 3e-4
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  crisis_threshold: 0.7
  buffer_size: 100000

# T-Cell 설정
tcell:
  contamination: 0.1
  n_estimators: 100
  window_size: 100

# Memory Cell 설정
memory:
  capacity: 1000
  k_neighbors: 5

# 온라인 학습 - 짧게 설정해서 100스텝 테스트
online_episodes: 3  # 3 에피소드만 실행 (약 200-300 스텝)
skip_offline: false
early_stopping_patience: 20

# 평가 설정
validation_freq: 2  # 2 에피소드마다 검증
save_freq: 100  # 100스텝마다 저장

# Ablation 설정
ablation:
  use_tcell: true
  use_memory: true
  use_xai: true
  offline_method: 'td3bc'

# 로깅
log_level: 'INFO'

# 목표 메트릭
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.25
  cvar_95: -0.02

# 베이스라인 비교
baselines:
  equal_weight:
    enabled: true
  standard_sac:
    enabled: false