# configs/default_irt.yaml
# IRT 기본 설정

seed: 42
device: auto # cpu|cuda|auto

# 데이터 설정
data:
  #
  symbols:
    [
      "AAPL",
      "MSFT",
      "JPM",
      "GS",
      "BA",
      "CAT",
      "MMM",
      "HON",
      "IBM",
      "NVDA",
      "KO",
      "MCD",
      "MRK",
      "MS",
      "NKE",
      "PG",
      "TRV",
      "UNH",
      "V",
      "VZ",
      "WMT",
      "CVX",
      "XOM",
      "AMGN",
      "AXP",
      "CRM",
      "CSCO",
      "DIS",
      "HD",
      "JNJ",
    ]
  start: "2008-01-01"
  end: "2020-12-31"
  test_start: "2021-01-01"
  test_end: "2024-12-31"
  val_ratio: 0.2
  interval: "1d"
  cache: true

# 환경 설정
env:
  initial_balance: 1000000
  transaction_cost: 0.001
  slippage: 0.0005
  max_leverage: 1.0
  max_turnover: 0.5  # 일일 최대 턴오버
  window_size: 20
  no_trade_band: 0.0  # 방안 2: 무거래 밴드 완전 제거 (기존 0.002 → 0.0)

# 특성 추출
feature_dim: 12

# BC (Behavioral Cloning) Warm-start (v2.1.0+)
bc:
  epochs: 30              # BC 학습 epoch 수 (vs IQL 50)
  batch_size: 256         # 배치 크기
  lr: 0.0003              # Adam learning rate
  log_interval: 5         # 로깅 간격
  diversity_noise: 0.15   # 프로토타입 다양화 노이즈 scale
  dirichlet_min: 1.0      # Dirichlet concentration minimum
  dirichlet_max: 100.0    # Dirichlet concentration maximum

# Legacy: 오프라인 IQL (deprecated, BC로 대체)
# offline:
#   method: "iql"
#   epochs: 50
#   steps_per_epoch: auto
#   batch_size: 256
#   expectile: 0.7
#   temperature: 1.0

# IRT 설정
irt:
  # 기본 구조
  emb_dim: 128 # 임베딩 차원
  m_tokens: 6 # 에피토프 토큰 수
  M_proto: 8 # 프로토타입 수
  alpha: 0.3 # OT-Replicator 결합 비율 (0=Replicator, 1=OT)

  # Diversity Regularization (v2.1.0+)
  lambda_div: 0.10 # KL divergence bonus weight

  # Sinkhorn 알고리즘 (Progressive Schedule)
  eps: 0.08        # Final epsilon (Stage 3, exploitation)
  eps_stage1: 0.15 # Stage 1 epsilon (0-1k steps, high exploration)
  eps_stage2: 0.10 # Stage 2 epsilon (1k-5k steps, moderate)
  max_iters: 10 # 최대 반복 횟수
  tol: 0.001 # 수렴 임계값

  # 비용 함수 가중치
  gamma: 0.5 # 공자극 가중치
  lambda_tol: 2.0 # 내성 가중치
  rho: 0.3 # 체크포인트 가중치

  # 위기 가열 메커니즘 (Replicator)
  eta_0: 0.05 # 기본 학습률
  eta_1: 0.15 # 위기 시 증가량 (0.10 → 0.15, 빠른 적응)

  # 자기-내성 (Tolerance)
  kappa: 1.0 # 내성 게인
  eps_tol: 0.1 # 내성 임계값
  n_self_sigs: 4 # 자기-내성 서명 개수

  # EMA 메모리
  ema_beta: 0.9 # 지수 이동 평균 계수

  # Progressive Exploration Schedule (v2.1.0+)
  progressive:
    stage1_steps: 1000       # Stage 1 boundary (high exploration)
    stage2_steps: 5000       # Stage 2 boundary (moderate)
    stage1_alpha_scale: 0.5  # Stage 1 concentration scaling
    stage2_alpha_scale: 0.7  # Stage 2 concentration scaling
    stage3_alpha_scale: 1.0  # Stage 3 concentration scaling (full)
    stage1_rnd_beta: 0.10    # Stage 1 RND novelty bonus
    stage2_rnd_beta: 0.05    # Stage 2 RND novelty bonus
    stage3_rnd_beta: 0.01    # Stage 3 RND novelty bonus

# REDQ 설정
redq:
  n_critics: 10 # 앙상블 크기
  m_sample: 2 # 서브셋 크기
  utd_ratio: 10 # Update-to-Data ratio
  hidden_dims: [256, 256]
  actor_lr: 0.0003
  critic_lr: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  buffer_size: 100000

# 학습 설정
online_episodes: 200
skip_offline: false

# Replay Buffer 설정
replay_buffer:
  alpha: 0.6 # PER 우선순위 지수
  beta: 0.4 # PER 중요도 샘플링

# 목적함수 설정 (PortfolioObjective)
objectives:
  sharpe_beta: 1.0
  sharpe_ema_alpha: 0.99
  cvar_alpha: 0.05
  cvar_target: -0.02
  lambda_cvar: 1.0
  lambda_turn: 0.01  # 0.1 → 0.01 (거래 유인 발생)
  lambda_dd: 0.0
  r_clip: 5.0

# 목표 메트릭
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.25
  cvar_95: -0.02

# 로깅
log_level: "INFO"
