seed: 42

data:
  symbols: ["AAPL","MSFT","BA","KO","VZ","INTC","WMT","DIS","JPM","HD","MCD","CVX","JNJ","PG","IBM","NKE","AXP","MMM","CAT","MRK","TRV","UNH","V","WBA","CSCO","PFE","XOM","WFC","GS","RTX"]
  start: "2012-01-01"
  end: "2024-12-31"
  interval: "1d"
  lookback: 20

env:
  transaction_cost_bps: 5
  no_trade_band: 0.001
  max_leverage: 1.0

t_cell:
  contamination: 0.1
  shap_topk: 5
  ema_alpha: 0.1

objectives:
  sharpe_eps: 1e-6
  cvar_alpha: 0.05
  cvar_target: -0.03
  reward_clip: 5.0
  turnover_bps: 5.0

b_cell:
  actor_lr: 3.0e-4
  critic_lr: 3.0e-4
  alpha_lr: 3.0e-4
  lambda_lr: 1.0e-3         # dual LR for lambda_cvar
  tau: 0.005
  gamma: 0.99
  batch_size: 256
  replay_size: 200000
  start_steps: 1000
  update_after: 1000
  update_every: 50
  target_entropy_scale: 0.5
  quantiles: 25
  cql_alpha: 0.2
  grad_clip_norm: 5.0
  max_steps: 100000

gating:
  z_to_lambda_scale: 1.0
  z_to_entropy_scale: 0.5

logging:
  out_dir: "runs/default"
  eval_every_steps: 5000
