# configs/research_sharpe_cvar.yaml
# BIPD 2.0 연구용 설정 - Sharpe + CVaR 최적화 강화

seed: 42
device: auto  # cpu|cuda|mps|auto

# 데이터 설정
data:
  symbols: [
    "AAPL", "MSFT", "AMZN", "NVDA", "GOOGL", "META", "TSLA", "BRK-B", "UNH", "JNJ",
    "V", "JPM", "WMT", "PG", "MA", "HD", "CVX", "MRK", "ABBV", "PFE",
    "KO", "PEP", "BAC", "TMO", "COST", "MCD", "DIS", "CSCO", "ACN", "ABT"
  ]  # 시가총액 상위 30
  start: "2008-01-01"
  end: "2020-12-31"
  test_start: "2021-01-01"
  test_end: "2024-12-31"
  interval: "1d"
  cache_dir: "data/cache"

# 특성 추출 설정 (연구용 확장)
features:
  window: 30  # 더 긴 윈도우
  indicators: [
    "returns", "vol_ema", "momentum", "rsi", "macd", "bollinger",
    "correlation", "beta", "skewness", "kurtosis", "value_at_risk"
  ]
  normalize: true
  use_pca: false  # PCA 차원 축소
  pca_components: 20

# 환경 설정 (더 엄격한 제약)
env:
  initial_capital: 1000000
  turnover_cost: 0.0015  # 15 bps (연구용 높은 비용)
  slip_coeff: 0.0008      # 더 높은 슬리피지
  no_trade_band: 0.003    # 0.3% 이하 변화 무시
  max_leverage: 1.0       # 레버리지 제한
  max_turnover: 0.4       # 더 엄격한 턴오버 제한
  min_holding_period: 2   # 최소 보유 기간 (일)

# T-Cell 설정 (앙상블 위기 감지)
tcell:
  method: "ensemble"  # iforest|bocpd|hmm|ensemble
  contamination: 0.08  # 더 민감한 이상치 감지
  n_estimators: 150    # 더 많은 트리
  ema_beta: 0.95       # 더 강한 평활
  shap_topk: 7         # 더 많은 특성 분석
  
  # BOCPD 설정
  bocpd_hazard_rate: 0.005
  bocpd_threshold: 0.6
  
  # HMM 설정
  hmm_n_states: 4  # 더 세밀한 레짐
  hmm_n_iter: 150
  
  crisis_thresholds:
    high: 0.65    # 더 민감한 임계값
    medium: 0.35

# B-Cell 설정 (연구용 강화)
bcell:
  # 오프라인 사전학습
  offline_algo: "iql"
  iql_expectile: 0.8  # 더 보수적
  iql_temperature: 2.5
  
  # 온라인 학습
  online_algo: "dist_sac_cql"
  
  # 네트워크 구조 (더 깊은 네트워크)
  actor_hidden: [512, 256, 128]
  critic_hidden: [512, 256, 128]
  n_quantiles: 64  # 더 많은 분위수
  
  # 학습률 (더 세밀한 튜닝)
  actor_lr: 1.0e-4
  critic_lr: 2.0e-4
  alpha_lr: 5.0e-4
  
  # SAC 파라미터
  gamma: 0.995  # 더 장기적 관점
  tau: 0.001    # 더 느린 타겟 업데이트
  alpha_init: 0.1
  alpha_min: 1.0e-4
  alpha_max: 0.3
  target_entropy_ratio: 0.95
  
  # CQL 설정 (더 강한 정규화)
  cql_alpha_start: 0.02
  cql_alpha_end: 0.1
  cql_num_samples: 16
  cql_lagrange: true  # Lagrangian CQL
  cql_target_action_gap: 5.0
  
  # Gradient clipping
  grad_clip: 0.5  # 더 강한 클리핑

# Memory Cell 설정 (확장)
memory:
  capacity: 1000  # 더 큰 메모리
  embedding_dim: 64  # 더 큰 임베딩
  similarity_threshold: 0.65
  k_neighbors: 7
  use_attention: true  # 어텐션 메커니즘
  temporal_decay: 0.995

# Gating Network 설정
gating:
  hidden_dim: 256
  temperature: 0.8  # 더 결정적
  min_dwell_steps: 10  # 더 긴 유지
  use_lstm: true  # LSTM 게이팅

# 목적함수 설정 (연구 중점)
objectives:
  # Differential Sharpe (강화)
  sharpe_beta: 2.0  # Sharpe 중요도 증가
  sharpe_ema_alpha: 0.995
  sharpe_epsilon: 1.0e-10
  
  # CVaR 제약 (더 엄격)
  cvar_alpha: 0.01  # 1% CVaR (극단적 꼬리)
  cvar_target: -0.015  # -1.5% 이상
  lambda_cvar: 2.0  # CVaR 페널티 강화
  
  # 추가 리스크 메트릭
  use_sortino: true
  sortino_mar: 0.02  # Minimum Acceptable Return
  
  use_calmar: true
  calmar_lookback: 252
  
  # 추가 페널티
  lambda_turn: 0.2  # 턴오버 페널티 강화
  lambda_dd: 0.1    # 낙폭 페널티 추가
  lambda_concentration: 0.05  # 집중도 페널티
  
  # 보상 정규화
  r_clip: 3.0  # 더 강한 클리핑
  reward_ema_alpha: 0.995
  
  # 다중 목적 가중치
  multi_objective_weights:
    sharpe: 0.4
    cvar: 0.3
    turnover: 0.2
    drawdown: 0.1

# 학습 설정 (연구용 확장)
train:
  # 오프라인 사전학습
  offline_steps: 300000  # 더 긴 사전학습
  offline_batch_size: 1024  # 더 큰 배치
  offline_eval_interval: 5000
  
  # 온라인 학습
  online_steps: 500000  # 더 긴 학습
  online_batch_size: 512
  
  # Experience replay
  buffer_size: 200000  # 더 큰 버퍼
  min_buffer_size: 5000
  prioritized_replay: true
  per_alpha: 0.7
  per_beta: 0.5
  per_beta_end: 1.0
  per_beta_steps: 400000
  
  # Reservoir sampling
  use_reservoir: true
  reservoir_size: 50000
  
  # 평가 및 저장
  eval_interval: 2500
  save_interval: 10000
  log_interval: 50
  
  # 조기 종료
  early_stop_patience: 100000
  early_stop_min_delta: 0.0005
  
  # 커리큘럼 학습
  curriculum_learning: true
  curriculum_stages:
    - steps: 100000
      turnover_limit: 0.5
      concentration_limit: 0.3
    - steps: 200000
      turnover_limit: 0.4
      concentration_limit: 0.25
    - steps: 300000
      turnover_limit: 0.3
      concentration_limit: 0.2

# 평가 설정
eval:
  episodes: 20  # 더 많은 평가
  benchmark: ["equal_weight", "market_cap", "risk_parity"]
  metrics: [
    "sharpe", "sortino", "calmar", "cvar", "var",
    "mdd", "turnover", "returns", "volatility",
    "information_ratio", "treynor_ratio"
  ]
  
  # 백테스트 설정
  backtest:
    rebalance_frequency: "daily"
    slippage_model: "linear"  # linear|square_root|market_impact
    commission_model: "tiered"  # flat|tiered|percentage
    
  # Walk-forward 분석
  walk_forward:
    enabled: true
    window_size: 252  # 1년
    step_size: 21    # 1개월
    min_train_size: 504  # 최소 2년

# 모니터링 설정 (연구용 강화)
monitoring:
  use_wandb: true
  wandb_project: "finflow-research"
  wandb_entity: "bipd-team"
  wandb_tags: ["sharpe", "cvar", "research"]
  
  # 안정성 체크 (더 엄격)
  q_value_check: true
  q_value_threshold: 50.0  # 더 낮은 임계값
  entropy_check: true
  entropy_min: 0.05  # 더 낮은 최소 엔트로피
  
  # StabilityMonitor 설정
  stability:
    enabled: true
    max_weight_change: 0.15  # 15% 최대 변화
    min_effective_assets: 5  # 최소 5개 자산
    log_interval: 50
    verbose: true  # 연구용 상세 로그
    
    # 이상치 감지 임계값
    n_sigma: 2.5  # 더 민감한 감지
    intervention_threshold: 2  # 더 빠른 개입
    
    # 체크포인트 롤백
    rollback_enabled: true
    rollback_window: 10000
  
  # 자동 개입 (더 적극적)
  auto_intervention: true
  intervention_actions:
    - reduce_learning_rate
    - increase_cql_alpha
    - increase_target_entropy
    - reset_optimizer
    - rollback_checkpoint
  
  # 실시간 플롯
  live_plotting: true
  plot_interval: 1000
  metrics_to_plot: [
    "sharpe_ratio", "cvar", "portfolio_value",
    "q_values", "entropy", "turnover"
  ]

# XAI 설정 (연구 분석 강화)
xai:
  enable_shap: true
  enable_counterfactual: true
  enable_regime_analysis: true
  enable_attribution: true
  
  # 리포트 생성
  report_frequency: 5  # 매 5 에피소드
  report_format: ["json", "html", "pdf"]
  
  # 반사실 분석
  counterfactual_scenarios: [
    {"volatility": -0.2},
    {"crisis_level": 0.3},
    {"correlation": -0.1},
    {"market_return": 0.05}
  ]
  
  # 특성 중요도 분석
  feature_importance_method: ["shap", "permutation", "gradient"]
  
  # 의사결정 추적
  decision_logging: true
  log_top_k_actions: 3
  log_confidence_threshold: 0.7

# 하이퍼파라미터 튜닝
hyperparameter_tuning:
  enabled: false  # 필요시 활성화
  method: "optuna"  # optuna|grid|random|bayesian
  n_trials: 100
  
  search_space:
    actor_lr: [1e-5, 1e-3]
    critic_lr: [1e-5, 1e-3]
    alpha_init: [0.01, 0.5]
    cql_alpha: [0.01, 0.2]
    n_quantiles: [16, 128]
    sharpe_beta: [0.5, 3.0]
    lambda_cvar: [0.5, 5.0]
  
  optimization_target: "sharpe_ratio"
  constraints:
    min_cvar: -0.02
    max_drawdown: 0.25

# 실험 메타데이터
experiment:
  name: "BIPD_2.0_Sharpe_CVaR_Research"
  description: "Sharpe ratio maximization with strict CVaR constraints"
  author: "BIPD Research Team"
  version: "2.0.0"
  tags: ["production", "sharpe", "cvar", "distributional_rl"]
  
  # 재현성
  deterministic: true
  benchmark_seeds: [42, 123, 456, 789, 2024]
  
  # 결과 저장
  save_predictions: true
  save_explanations: true
  save_replay_buffer: false  # 용량 고려