seed: 42

data:
  symbols: ["AAPL","MSFT","BA","KO","VZ","INTC","WMT","DIS","JPM","HD","MCD","CVX","JNJ","PG","IBM","NKE","AXP","MMM","CAT","MRK","TRV","UNH","V","WBA","CSCO","PFE","XOM","WFC","GS","RTX"]
  start: "2008-01-01"
  end: "2024-12-31"
  interval: "1d"
  lookback: 20

env:
  transaction_cost_bps: 7
  no_trade_band: 0.001
  max_leverage: 1.0

t_cell:
  contamination: 0.12
  shap_topk: 7
  ema_alpha: 0.07

objectives:
  sharpe_eps: 1e-6
  cvar_alpha: 0.05
  cvar_target: -0.04
  reward_clip: 4.0
  turnover_bps: 7.0

b_cell:
  actor_lr: 2.0e-4
  critic_lr: 2.0e-4
  alpha_lr: 2.0e-4
  lambda_lr: 1.0e-3
  tau: 0.005
  gamma: 0.995
  batch_size: 256
  replay_size: 300000
  start_steps: 1500
  update_after: 1500
  update_every: 50
  target_entropy_scale: 0.4
  quantiles: 31
  cql_alpha: 0.3
  grad_clip_norm: 5.0
  max_steps: 150000

gating:
  z_to_lambda_scale: 1.2
  z_to_entropy_scale: 0.7

logging:
  out_dir: "runs/research_sharpe_cvar"
  eval_every_steps: 4000
