# configs/test_quick.yaml
# 빠른 테스트용 설정 (10 에피소드)

seed: 42
device: auto

# 데이터 설정 (축소)
data:
  symbols: [
      "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA"  # 5개 종목만
    ]
  start: "2018-01-01"  # 더 짧은 기간
  end: "2019-12-31"
  test_start: "2020-01-01"
  test_end: "2020-12-31"
  val_ratio: 0.2
  interval: "1d"
  cache: true

# 환경 설정 (수정된 값)
env:
  initial_balance: 1000000
  transaction_cost: 0.001
  slippage: 0.0005
  no_trade_band: 0.01  # 수정됨: 0.002 → 0.01
  max_leverage: 1.0
  max_turnover: 0.5
  window_size: 20
  use_advanced_reward: false

feature_dim: 12

# 오프라인 학습 (축소)
offline:
  method: "iql"
  epochs: 5  # 50 → 5
  batch_size: 256
  expectile: 0.7
  temperature: 1.0  # 수정됨: 3.0 → 1.0
  bc_weight: 2.5
  policy_delay: 2
  normalize_q: true

# B-Cell (수정된 값)
bcell:
  algorithm: "REDQ"
  hidden_dims: [256, 256]  # 원래 크기 유지 (오프라인과 일치)
  n_critics: 5  # 10 → 5
  m_sample: 2
  utd_ratio: 10  # 수정됨: 20 → 10
  n_quantiles: 25
  top_quantiles_to_drop_per_net: 2
  quantile_embedding_dim: 64

  actor_lr: 3e-4
  critic_lr: 3e-4
  alpha_lr: 3e-4
  batch_size: 256

  gamma: 0.99
  tau: 0.005
  alpha: 0.1  # 수정됨: 0.2 → 0.1

  crisis_threshold: 0.7
  buffer_size: 10000  # 100000 → 10000

  dirichlet:
    concentration_init: 1.0
    concentration_min: 0.1
    concentration_max: 10.0
    epsilon: 1e-6

# T-Cell
tcell:
  contamination: 0.1
  n_estimators: 50  # 100 → 50
  window_size: 50  # 100 → 50

# Memory Cell
memory:
  capacity: 100  # 1000 → 100
  k_neighbors: 3  # 5 → 3

# 학습 설정 (축소)
online_episodes: 10  # 200 → 10
skip_offline: false
early_stopping_patience: 5  # 20 → 5

# Ablation study
ablation:
  use_tcell: true
  use_memory: true
  use_xai: true
  offline_method: "iql"

# 모니터링 설정
monitoring:
  use_tensorboard: false  # 빠른 테스트를 위해 비활성화
  use_wandb: false
  wandb_project: "finflow-rl-test"
  wandb_entity: null
  log_frequency: 1  # 10 → 1

  stability_check:
    enabled: true
    q_value_threshold: 1000.0
    gradient_clip: 0.5  # 수정됨: 1.0 → 0.5
    check_frequency: 10  # 100 → 10

# 분포적 RL 설정
distributional:
  n_quantiles: 16  # 32 → 16
  kappa: 1.0
  risk_measure: "neutral"
  risk_param: 0.1
  quantile_embedding_dim: 32  # 64 → 32

# 기타
log_level: "INFO"
save_freq: 10  # 100 → 10

# 목적함수 설정
objectives:
  sharpe_beta: 1.0
  sharpe_ema_alpha: 0.99
  sharpe_epsilon: 1.0e-8
  cvar_alpha: 0.05
  cvar_target: -0.02
  lambda_cvar: 1.0
  lambda_turn: 0.1
  lambda_dd: 0.0
  r_clip: 5.0
  reward_ema_alpha: 0.99

# 목표 메트릭
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.25
  cvar_95: -0.02

# 베이스라인 설정
baselines:
  equal_weight:
    enabled: false  # 빠른 테스트를 위해 비활성화
  standard_sac:
    enabled: false  # 빠른 테스트를 위해 비활성화
    n_episodes: 10
    hidden_dims: [256, 256]