# configs/test_1episode.yaml
# 1 episode 테스트용 설정 (default.yaml과 동일하되 에피소드만 1로)

seed: 42
device: cpu  # 빠른 테스트를 위해 CPU 사용

# 데이터 설정
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
  period: '2y'  # 적당한 기간
  interval: '1d'
  cache: true

# 환경 설정
env:
  initial_balance: 1000000
  transaction_cost: 0.001
  max_leverage: 1.0
  window_size: 20

# 특성 추출
feature_dim: 12

# 오프라인 학습 (최소화)
offline:
  method: 'iql'  # 'iql' or 'td3bc'
  epochs: 1  # 1 epoch만
  batch_size: 256  # default와 동일

  # IQL 전용
  expectile: 0.7
  temperature: 3.0

  # TD3+BC 전용
  bc_weight: 2.5
  policy_delay: 2
  normalize_q: true

# B-Cell (REDQ) - default와 동일
bcell:
  # 네트워크
  hidden_dims: [256, 256]

  # REDQ 설정 (논문 권장값)
  n_critics: 10  # 원논문 권장: N=10 (기존 5에서 증가)
  m_sample: 2
  utd_ratio: 20

  # 학습
  actor_lr: 3e-4
  critic_lr: 3e-4
  alpha_lr: 3e-4
  batch_size: 256

  # RL
  gamma: 0.99
  tau: 0.005
  alpha: 0.2

  # 위기 대응
  crisis_threshold: 0.7

  # 버퍼
  buffer_size: 100000

# T-Cell - default와 동일
tcell:
  contamination: 0.1
  n_estimators: 100
  window_size: 100

# Memory Cell - default와 동일
memory:
  capacity: 1000
  k_neighbors: 5

# 학습 설정
online_episodes: 1  # ⭐ 핵심 변경 - 1 episode만
skip_offline: false  # 오프라인도 테스트
early_stopping_patience: 20

# Ablation study - default와 동일
ablation:
  use_tcell: true
  use_memory: true
  use_xai: true
  offline_method: 'iql'

# 기타 - default와 동일
log_level: 'INFO'
save_freq: 10

# 목표 메트릭 - default와 동일
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.25
  cvar_95: -0.02

# 베이스라인 설정 - default와 동일
baselines:
  equal_weight:
    enabled: true
  standard_sac:
    enabled: true
    n_episodes: 100
    hidden_dims: [256, 256]